# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b37eff6e472f3bde27210aa9c231b694239b84d9dda63e30a8feddd979be26d58a5058a89bfdeec95f214c0d3d61da03ec07bcfb3a43daad126e54fc2ed08373

test:
  secret_key_base: d7dc8ed7b74f78ed6b4e729bc1c3daedb10b7cea5bd861bdb2498dd09d8a25fdadf2ea0e6c765ff24a6a82b130e2c5b450d488d98d13871ffed4e85f8ca053f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
